# Site settings
title: Charlie's Reflections
email: forcemz@outlook.com
description: "Start now to change the world"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://forcemz.net" # the base hostname & protocol for your site
twitter_username: sinont
github_username:  fcharlie

# Build settings
markdown: kramdown
